### ISSUE TITLE
Data set annotation

### ISSUE THREAD

**Issue by lxw-Chichester** [zju3dv/OnePose#22]
Congratulations on your achievement. I would like to ask about the production of data sets, how to mark poses and boxes

**Comment by siatheindochinese** [comment]
The authors mentioned in the paper that open-source AR tools like ARKit or ARCore can be used to annotate the images.

**Comment by lxw-Chichester** [comment]
> The authors mentioned in the paper that open-source AR tools like ARKit or ARCore can be used to annotate the images.
How to get accurate pose labeling

**Comment by DeriZSY** [comment]
> Congratulations on your achievement. I would like to ask about the production of data sets, how to mark poses and boxes

Hi, thanks for your interest in our work. This is indeed an interesting and non-trivial question. As discussed in the paper and supp material, we obtained object pose in the following way:
1) The camera poses for each frame can be obtained from AR tools.
2) We manually annotate the bounding box for each sequence in the world frame as the AR anchor whose pose is fixed with respect to the world frame. Then the object poses for each frame can be computed with camera poses and the pose of the annotated box.

The tricky part lies here: the 'absolutely correct' object pose annotation does not exist anyway as the object pose is defined with respect to the object coordinate frame. 

Thus the only important thing is to guarantee that the definition of the object coordinate frame is consistent through different sequences for each same object. This can be achieved by joint bundle adjustment and can be evaluated visually by projecting reconstructed keypoints from on sequence to another as described in the supplementary material.

Feel free to re-open the issue if you have any further questions.
